### ISSUE TITLE
Index link should be conditional

### ISSUE THREAD

**Issue by davidfarmer** [siefkenj/pretext-react#6]
The navbar button for the index should only be inserted if there is an index.
Line 91 of App.tsx
(Seems to require an index entry in the manifest(?))

Also, the navActions in index-button.tsx is not done properly.

**Comment by siefkenj** [comment]
What do you mean by "done properly"?

If the index is missing from manifest, it should be added...

**Comment by davidfarmer** [comment]
One of the things I mean is not hard code "index-1.html" .

**Comment by siefkenj** [comment]
Oh! You're filing an issue against future code. I get it now.

**Comment by siefkenj** [comment]
@davidfarmer How many indices can there be? If I search `doc-manifest.xml` for `type="index"` and link to the first on found (if any) would that be the proper algorithm?

**Comment by siefkenj** [comment]
Fixed in #27 

The algorithm I use: take the first `type=index` item that is found in `doc-manifest.xml` and use that for the index button. If no such item is found, there is no index button.
